//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 学员入住宿舍信息表
    /// </summary>
    [Table("Accdationinformation")]
    public partial class Accdationinformation
    {      
        [Key]
        public int ID { get; set; }

        /// <summary>
        /// 入住时间
        /// </summary>
        public DateTime StayDate { get; set; }

        /// <summary>
        /// 结束时间
        /// </summary>
        public Nullable<System.DateTime> EndDate { get; set; }

        public string Studentnumber { get; set; }

        /// <summary>
        /// 床位id
        /// </summary>
        public int BedId { get; set; }

        public string Remark { get; set; }
        public bool IsDel { get; set; }

        /// <summary>
        ///房间id
        /// </summary>
        public int DormId { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreationTime { get; set; }

    }
}
