//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("AttendanceInfo")]
    public partial class AttendanceInfo
    {
        [Key]
        public int AAttendanceId { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> YearAndMonth { get; set; }
        public Nullable<decimal> ToRegularDays { get; set; }
        public Nullable<decimal> LeaveDays { get; set; }
        public Nullable<int> DaysOffNum { get; set; }
        public Nullable<int> WorkAbsentNum { get; set; }
        public string WorkAbsentRecord { get; set; }
        public Nullable<int> OffDutyAbsentNum { get; set; }
        public string OffDutyAbsentRecord { get; set; }
        public Nullable<int> TardyNum { get; set; }
        public string TardyRecord { get; set; }
        public Nullable<int> LeaveEarlyNum { get; set; }
        public string LeaveEarlyRecord { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
    }
}
