//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    /// 课件巡班记录表
    /// </summary>
    [Table("Break")]
    public partial class Break
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 班级编号
        /// </summary>
        public int ClassSchedule_Id { get; set; }     
        /// <summary>
        /// 巡班时间段
        /// </summary>
        public Nullable<int> BaseDataEnum_Id { get; set; }
        /// <summary>
        /// 添加日期
        /// </summary>
        public Nullable<System.DateTime> RecodeDate { get; set; }
        /// <summary>
        /// 备注说明
        /// </summary>
        public string Rmark { get; set; }
        
        public Nullable<bool> IsDelete { get; set; }

        /// <summary>
        /// 违纪类型编号
        /// </summary>
        public int Violationofdiscipline_Id { get; set; }

       /// <summary>
       /// 登记人
       /// </summary>
        public string Emp_Id { get; set; }

        /// <summary>
        /// 违纪人数
        /// </summary>
        public int Count { get; set; }
    }
}
