//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    /// 渠道员工表
    /// </summary>
    [Table("ChannelStaff")]
    public partial class ChannelStaff
    {
        [Key]
        public int ID { get; set; }
        /// <summary>
        /// 员工id
        /// </summary>
        public string EmployeesInfomation_Id { get; set; }
        /// <summary>
        /// 注册时间
        /// </summary>
        public System.DateTime ChannelDate { get; set; }
        /// <summary>
        /// 是否删除
        /// </summary>
        public Nullable<bool> IsDel { get; set; }
        /// <summary>
        /// 离职时间
        /// </summary>
        public Nullable<System.DateTime> QuitDate { get; set; }


    }
}
