//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    /// 班级表
    /// </summary>
    [Table("ClassSchedule")]
    public partial class ClassSchedule
    {
       /// <summary>
        /// 班级id
        /// </summary>
        [Key]
        public int id { get; set; }
        /// <summary>
        /// 编号
        /// </summary>
        public string ClassNumber { get; set; }
        /// <summary>
        /// 班级状态 false为未毕业班 true为毕业班
        /// </summary>
        public Nullable<bool> ClassStatus { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string ClassRemarks { get; set; }
        /// <summary>
        /// 是否删除 false 存在 true 停用
        /// </summary>
        public Nullable<bool> IsDelete { get; set; }
    
        /// <summary>
        /// 专业id
        /// </summary>
        public Nullable<int> Major_Id { get; set; }
        /// <summary>
        /// 阶段id
        /// </summary>
        public int grade_Id { get; set; }
        /// <summary>
        /// 上课时间段
        /// </summary>
        public Nullable<int> BaseDataEnum_Id { get; set; }
        /// <summary>
        /// 班级状态，升学！
        /// </summary>
        public int? ClassstatusID { get; set; }
    }
}

