//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Classroom")]
    public partial class Classroom
    {
        [Key]
        public int Id { get; set; }
        public string ClassroomName { get; set; }
        public Nullable<int> Count { get; set; }
        public string Rmark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        /// <summary>
        /// 所属校区
        /// </summary>
        public Nullable<int> BaseData_Id { get; set; }
    }
}
