//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 教室表
    /// </summary>
    [Table("Classroom")]
    public partial class Classroom
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 教室名称
        /// </summary>
        public string ClassroomName { get; set; }
        /// <summary>
        /// 座位数
        /// </summary>
        public Nullable<int> Count { get; set; }
        /// <summary>
        /// 说明
        /// </summary>
        public string Rmark { get; set; }
        /// <summary>
        /// 是否禁用(false--不禁用，true--已禁用)
        /// </summary>
        public Nullable<bool> IsDelete { get; set; }
        /// <summary>
        /// 所属校区
        /// </summary>
        public Nullable<int> BaseData_Id { get; set; }
    }
}
