//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    /// 班级表
    /// </summary>
    [Table("ClassSchedule")]
    public partial class ClassSchedule
    {
        
      [Key]
        public string ClassNumber { get; set; }
        public Nullable<bool> ClassStatus { get; set; }
        public string ClassRemarks { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Major_Id { get; set; }
        public Nullable<int> grade_Id { get; set; }
        public Nullable<int> BaseDataEnum_Id { get; set; }
    }
}

