//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("ClassTeacherKeep")]
    public partial class ClassTeacherKeep
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 班主任员工编号
        /// </summary>
        public string Headmaster_Id { get; set; } //去数据库修改
        /// <summary>
        /// 值班类型
        /// </summary>
        public int BeOnDutyType_Id { get; set; }
        /// <summary>
        /// 值班情况
        /// </summary>
        public string BySituation { get; set; }
 
        public Nullable<bool> IsDelete { get; set; }
        /// <summary>
        /// 值班日期
        /// </summary>
        public DateTime ByDate { get; set; }

        public string Rmark { get; set; }
    }
}
