//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 教员带班
    /// </summary>
    [Table("ClassTeacher")]
    public partial class ClassTeacher
    {
        [Key]
        public int ID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        /// <summary>
        /// 课程id
        /// </summary>
        public Nullable<int> Skill { get; set; }

        /// <summary>
        /// 班级ID
        /// </summary>
        public int ClassNumber { get; set; }
        public Nullable<bool> IsDel { get; set; }

        public DateTime BeginDate { get; set; }

        public Nullable<DateTime> EndDate { get; set; }
    }
}
