//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    /// 咨询师表
    /// </summary>
    [Table("ConsultTeacher")]
    public partial class ConsultTeacher
    {
        
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 咨询师绑定的员工编号
        /// </summary>
        public string Employees_Id { get; set; }
        /// <summary>
        /// 咨询级别
        /// </summary>
        public Nullable<int> ConGrade { get; set; }
        /// <summary>
        /// 说明
        /// </summary>
        public string Rmark { get; set; }
        /// <summary>
        /// 是否
        /// </summary>
        public Nullable<bool> IsDelete { get; set; }
       
        public string BrainImage { get; set; }
    }
}
