//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    /// 分量表
    /// </summary>
    [Table("Consult")]
    public partial class Consult
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 咨询师编号
        /// </summary>
        public int TeacherName { get; set; }
        /// <summary>
        /// 数据备案编号
        /// </summary>
        public int StuName { get; set; }
        /// <summary>
        /// 说明
        /// </summary>
        public string Rmark { get; set; }
         
        public Nullable<bool> IsDelete { get; set; }
        /// <summary>
        /// 分量日期
        /// </summary>
        public Nullable<System.DateTime> ComDate { get; set; }
    
    }
}
