//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("ConvertCourse")]
    public partial class ConvertCourse
    {
        [Key]
        public int Id { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        /// <summary>
        /// 申请人
        /// </summary>
        public Nullable<int> TeacherID { get; set; }
        public string Reason { get; set; }

        /// <summary>
        /// 上课老师
        /// </summary>
        public Nullable<int> AttendClassTeacher { get; set; }
        public string ClassNumber { get; set; }
        public Nullable<System.DateTime> BeforDate { get; set; }
        public Nullable<System.DateTime> AfterDate { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }

        /// <summary>
        /// 上午 下午
        /// </summary>
        public string BefoDaterSpecific { get; set; }

        /// <summary>
        /// 上午 下午
        /// </summary>
        public string AfterDateSpecific { get; set; }


    }
}
