//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("CooperaEnterprises")]
    public partial class CooperaEnterprises
    {
        [Key]
        public int ID { get; set; }
        public string EntContacts { get; set; }
        public string EntPhone { get; set; }
        /// <summary>
        /// 是否处于合作关系，false不合作 true 合作
        /// </summary>
        public Nullable<bool> IsCooper { get; set; }
        public string Remark { get; set; }

        public Nullable<System.DateTime> Date { get; set; }
    }
}
