//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    /// 课程时间表
    /// </summary>
    [Table("CourseTime")]
    public partial class CourseTime
    {
        /// <summary>
        /// 课程时间编号
        /// </summary>
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 基础数据枚举类型表的值
        /// </summary>
        public Nullable<int> BaseDataEnum_Id { get; set; }
        /// <summary>
        /// 课时数
        /// </summary>
        public Nullable<int> CourseCount { get; set; }
        /// <summary>
        /// 其他说明
        /// </summary>
        public string Rmark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public Nullable<System.DateTime> AddDate { get; set; }
    
    }
}
