//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        
    
        public int CurriculumID { get; set; }
        public Nullable<int> Grand_Id { get; set; }
        public Nullable<int> MajorID { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CourseType_Id { get; set; }
        public Nullable<int> CourseCount { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<decimal> PeriodMoney { get; set; }
        public string Rmark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
    }
}
