//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    /// 借资表
    /// </summary>
    [Table("Debit")]
    public partial class Debit
    {
        [Key]
        public int ID { get; set; }
        public string EmpNumber { get; set; }
        public double DebitMoney { get; set; }
        public string Debitwhy { get; set; }
        public string Remark { get; set; }
        public bool IsDel { get; set; }
        /// <summary>
        /// 借款时间
        /// </summary>
        public System.DateTime date { get; set; }
    
    }
}
