//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    /// 学员保险表
    /// </summary>
    [Table(name: "DetailedStudentIn")]
    public partial class DetailedStudentIn
    {
        /// <summary>
        /// 保险id
        /// </summary>
        [Key]
        public int ID { get; set; }
        /// <summary>
        /// 保额（费用）
        /// </summary>
        public Nullable<double> InsurancePremium { get; set; }
        /// <summary>
        /// 开始保期
        /// </summary>
        public Nullable<System.DateTime> Starttime { get; set; }
        /// <summary>
        /// 到期保期
        /// </summary>
        public Nullable<System.DateTime> Endtime { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remarks { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public Nullable<System.DateTime> Addtime { get; set; }
        /// <summary>
        /// 学号
        /// </summary>
        public string StudentID { get; set; }
    
    }
}
