//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "DimissionApply")]
    public partial class DimissionApply
    {
        [Key]
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> DimissionDate { get; set; }
        public string OpinionOrAdvice { get; set; }
        public Nullable<bool> IsPass { get; set; }
        public Nullable<bool> IsApproval { get; set; }
        public string DimissionReason { get; set; }
    }
}
