//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 宿舍房间信息
    /// </summary>
    [Table(name: "DormInformation")]
    public partial class DormInformation
    {
        /// <summary>
        /// 主键id
        /// </summary>
        [Key]
        public int ID { get; set; }
        /// <summary>
        /// 0的意思是房间类型不是学生入住的，1为男生，2为女生
        /// </summary>
        public int SexType { get; set; }
        /// <summary>
        /// 栋楼层id
        /// </summary>
        public int TungFloorId { get; set; }
        /// <summary>
        /// 房间类型id
        /// </summary>
        public int RoomStayTypeId { get; set; }
        /// <summary>
        /// false可用，true 不可用
        /// </summary>
        public bool IsDelete { get; set; }

        public string Remark { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreationTime { get; set; }
        /// <summary>
        ///房间号码
        /// </summary>
        public string DormInfoName { get; set; }


        /// <summary>
        /// 房间数量id
        /// </summary>
        public int RoomStayNumberId { get; set; }

        /// <summary>
        /// 方向左右，false为左，true为右
        /// </summary>
        public bool Direction { get; set; }

        /// <summary>
        /// 禁用原因
        /// </summary>
        public string ProhibitRemark { get; set; }
    }
}
