//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "EmploySituation")]
    public partial class EmploySituation
    {
       [Key]
        public int ID { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string StudentNO { get; set; }

        /// <summary>
        /// 未就业原因
        /// </summary>
        public string NoReasons { get; set; }
        public Nullable<int> EntinfoID { get; set; }
        /// <summary>
        /// 实际工资
        /// </summary>
        public string RealWages { get; set; }

        /// <summary>
        /// 记录人
        /// </summary>
        public int empid { get; set; }
    }
}
