//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    /// <summary>
    /// 毕业季度参与的班级中间表
    /// </summary>
    [Table(name: "EmpQuarterClass")]
    public partial class EmpQuarterClass
    {
        [Key]
        public int ID { get; set; }
        public int QuarterID { get; set; }
        public string ClassNO { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }

    }
}
