//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 就业专员带学员记录
    /// </summary>
    [Table(name: "EmpStaffAndStu")]
    public partial class EmpStaffAndStu
    {
        [Key]
        public int ID { get; set; }
        /// <summary>
        /// 就业专员id
        /// </summary>
        public Nullable<int> EmpStaffID { get; set; }
        /// <summary>
        /// 学生id
        /// </summary>
        public string  Studentno { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsDel { get; set; }

        /// <summary>
        /// 季度id
        /// </summary>
        public int QuarterID { get; set; }

        /// <summary>
        ///就业阶段 1：第一次就业 2：第二次就业
        /// </summary>
        public int EmploymentStage { get; set; }

        /// <summary>
        /// 就业状态 1：就业中 2：已就业 3：未就业
        /// </summary>
         public int EmploymentState { get; set; }

        /// <summary>
        /// 是否正在带 true 带 false 不带
        /// </summary>
        public bool Ising { get; set; }
    }
}
