//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "EmpTransaction")]
    public partial class EmpTransaction
    {
        [Key]
        public int TransactionId { get; set; }
        public string EmployeeId { get; set; }
        public string TransactionType { get; set; }
        public Nullable<System.DateTime> TransactionTime { get; set; }
        public string PreviousDept { get; set; }
        public string PreviousPosition { get; set; }
        public string PresentDept { get; set; }
        public string PresentPosition { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
    }
}
