//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 企业专业表
    /// </summary>
    [Table(name: "EntSpee")]
    public partial class EntSpee
    {
        [Key]
        public int Id { get; set; }
        public int EntID { get; set; }
        public int SpeID { get; set; }
        public Nullable<System.DateTime> SpeeDate { get; set; }
        public string Remark { get; set; }
        public string JobResponsibilities { get; set; }
        public string Requirements { get; set; }
        public string EntSalary { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
    }
}
