//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "Examination")]
    public partial class Examination
    {
        [Key]
        public int ID { get; set; }

        public string Title { get; set; }
        public string ExamNo { get; set; }
        /// <summary>
        /// 时限
        /// </summary>
        public int TimeLimit { get; set; }
        /// <summary>
        /// 考试类型
        /// 阶段考试.
        /// 升学考试
        /// </summary>
        public int ExamType { get; set; }
        public string   Remark { get; set; }

        /// <summary>
        /// 开始时间
        /// </summary>
        public DateTime BeginDate { get; set; }

        public int PaperLevel { get; set; }


    }
}
