//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 考场
    /// </summary>
    [Table(name: "ExaminationRoom")]
    public partial class ExaminationRoom
    {
        [Key]
        public int ID { get; set; }
        /// <summary>
        /// 教室ID
        /// </summary>
        public Nullable<int> Classroom_Id { get; set; }
        /// <summary>
        /// 监考员1
        /// </summary>
        public string  Invigilator1 { get; set; }
        /// <summary>
        /// 监考员2
        /// </summary>
        public string Invigilator2 { get; set; }
        public string Remark { get; set; }
        /// <summary>
        /// 所属考试
        /// </summary>
        public Nullable<int> Examination { get; set; }

       


    }
}
