//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "ExamRoomDistributed")]
    public partial class ExamRoomDistributed
    {
        [Key]
        public int ID { get; set; }
        /// <summary>
        /// 考生考号
        /// </summary>
        public string CandidateNumber { get; set; }
        /// <summary>
        /// 考场ID
        /// </summary>
        public Nullable<int> ExaminationRoom { get; set; }
        /// <summary>
        /// 所属考试
        /// </summary>
        public int ExamID { get; set; }


    }
}
