//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiveroutines
    {
        public int ID { get; set; }
        public Nullable<int> Lateformorningclasses { get; set; }
        public Nullable<int> Unqualifieddormitoryservice { get; set; }
        public Nullable<int> Notreturningtotime { get; set; }
        public Nullable<int> NumberofClassroomViolations { get; set; }
        public Nullable<int> Headmaster { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remarks { get; set; }
    }
}
