//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 咨询跟踪表
    /// </summary>
    [Table(name: "FollwingInfo")]
    public partial class FollwingInfo
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 分量编号
        /// </summary>
        public Nullable<int> Consult_Id { get; set; }        
        /// <summary>
        /// 咨询内容
        /// </summary>
        public string TailAfterSituation { get; set; }
        /// <summary>
        /// 跟踪日期
        /// </summary>
        public Nullable<System.DateTime> FollwingDate { get; set; }
        /// <summary>
        /// 说明
        /// </summary>
        public string Rmark { get; set; }
         
        public Nullable<bool> IsDelete { get; set; }
    
    }
}
