//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 老师擅长的课程
    /// </summary>
    [Table(name: "GoodSkill")]
    public partial class GoodSkill
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 教员ID
        /// </summary>
        public Nullable<int> TearchID { get; set; }
        /// <summary>
        /// 课程
        /// </summary>
        public Nullable<int> Curriculum { get; set; }
        public string Remark { get; set; }
    
    
    }
}
