//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 阶段表
    /// </summary>
    [Table(name: "Grand")]
    public partial class Grand
    {

        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 阶段名称
        /// </summary>
        public string GrandName { get; set; }
        /// <summary>
        /// 是否删除
        /// </summary>
        public Nullable<bool> IsDelete { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Reaks { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public Nullable<System.DateTime> AddDate { get; set; }


        public static bool IsInList(List<Grand> sources, Grand grand)
        {
            foreach (var item in sources)
            {
                if (item.Id == grand.Id)
                    return true;
            }
            return false;
        }

    }
}
