//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    /// 学员家长访谈记录
    /// </summary>
    [Table(name: "InterviewRecordsof")]
    public partial class InterviewRecordsof
    {
        [Key]
        public int ID { get; set; }
        /// <summary>
        /// 访谈话题
        /// </summary>
        public string InterviewTopics { get; set; }
        /// <summary>
        /// 访谈内容
        /// </summary>
        public string Interviewcontent { get; set; }
        /// <summary>
        /// 访谈日期
        /// </summary>
        public DateTime Interviewtime { get; set; }
        /// <summary>
        /// 学员id
        /// </summary>
        public string Studentnumber { get; set; }
        /// <summary>
        /// 家长姓名
        /// </summary>
        public string Parent { get; set; }
        /// <summary>
        /// 登记人
        /// </summary>
        public string Empnumber { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remarks { get; set; }
        /// <summary>
        /// 是否禁用
        /// </summary>
        public Nullable<bool> IsDelete { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public DateTime Addtime { get; set; }


    }
}
