//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "InterviewRecordsof")]
    public partial class InterviewRecordsof
    {
        [Key]
        public int ID { get; set; }
        public string InterviewTopics { get; set; }
        public string Interviewcontent { get; set; }
        public Nullable<System.DateTime> Interviewtime { get; set; }
        public string Studentnumber { get; set; }
        public string Parent { get; set; }
        public Nullable<int> Headmaster { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
    
        public virtual Headmaster Headmaster1 { get; set; }
        public virtual StudentInformation StudentInformation { get; set; }
    }
}
