//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "IsGoodOrBad")]
    public partial class IsGoodOrBad
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> Check_Id { get; set; }
        public Nullable<int> Goods_Id { get; set; }
        public Nullable<System.DateTime> FindDate { get; set; }
        public Nullable<bool> IsOK { get; set; }
        public string Cause { get; set; }
        public Nullable<bool> IsHandle { get; set; }
        public string Note { get; set; }
    
        
    }
}
