//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "MarketChair")]
    public partial class MarketChair
    {
        [Key]
        public int Id { get; set; }
        public string TerCharName { get; set; }
        public string ChairName { get; set; }
        public Nullable<int> ManCount { get; set; }
        public string ChairAddress { get; set; }
        public Nullable<System.DateTime> ChairTime { get; set; }
        public string Employees_Id { get; set; }
        public string Rmark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        
    }
}
