//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeritsCheck
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> YearAndMonth { get; set; }
        public string RoutineWork { get; set; }
        public Nullable<decimal> RoutineWorkPropotion { get; set; }
        public Nullable<decimal> RoutineWorkFillRate { get; set; }
        public string OtherWork { get; set; }
        public Nullable<decimal> OtherWorkPropotion { get; set; }
        public Nullable<decimal> OtherWorkFillRate { get; set; }
        public Nullable<decimal> SelfReportedScore { get; set; }
        public Nullable<decimal> SuperiorGrade { get; set; }
        public Nullable<decimal> FinalGrade { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
       
    }
}
