//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "MeritsCheck")]
    public partial class MeritsCheck
    {
        [Key]
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> YearAndMonth { get; set; }
        public string RoutineWork { get; set; }//日常工作内容
        public Nullable<decimal> RoutineWorkPropotion { get; set; }//日常工作权重占比
        public Nullable<decimal> RoutineWorkFillRate { get; set; }//日常工作完成率
        public string OtherWork { get; set; }//其他或领导临时指派任务
        public Nullable<decimal> OtherWorkPropotion { get; set; }//其他工作权重占比
        public Nullable<decimal> OtherWorkFillRate { get; set; }//其他工作完成率
        public Nullable<decimal> SelfReportedScore { get; set; }//自评得分
        public Nullable<decimal> SuperiorGrade { get; set; }//上级评分
        public Nullable<decimal> FinalGrade { get; set; }//最终绩效分
        public string Remark { get; set; }//备注
        public Nullable<bool> IsDel { get; set; }
        public Nullable<bool> IsApproval { get; set; }

    }
}
