//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlySalaryRecord
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> YearAndMonth { get; set; }
        public Nullable<decimal> AttendanceDay { get; set; }
        public Nullable<decimal> BaseSalary { get; set; }
        public Nullable<decimal> PositionSalary { get; set; }
        public Nullable<int> PerformanceScore { get; set; }
        public Nullable<decimal> PerformanceSalary { get; set; }
        public string NetbookSubsidy { get; set; }
        public Nullable<decimal> OvertimeCharges { get; set; }
        public Nullable<decimal> LeaveDays { get; set; }
        public Nullable<decimal> OtherDeductions { get; set; }
        public string PersonalSocialSecurity { get; set; }
        public string SocialSecuritySubsidy { get; set; }
        public Nullable<decimal> PersonalIncomeTax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> PayCardSalary { get; set; }
        public Nullable<decimal> CasehSalary { get; set; }
    
       
    }
}
