//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "NetClientRecord")]
    public partial class NetClientRecord
    {
        [Key]
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> NetClientDate { get; set; }
        public string MarketTeaId { get; set; }
        public string StuName { get; set; }
        public Nullable<bool> StuSex { get; set; }
        public Nullable<int> StuAge { get; set; }
        public string InformationSource { get; set; }
        public string Education { get; set; }
        public string Region { get; set; }
        public string ContactInformation { get; set; }
        public string QQNum { get; set; }
        public string WeChatNum { get; set; }
        public Nullable<bool> IsFaceConsult { get; set; }
        public string CallBackCase { get; set; }
        public string SecondCallBack { get; set; }
        public string ThirdCallBack { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        
    }
}
