//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "NetClientRecord")]
    public partial class NetClientRecord
    {
        [Key]
        public int Id { get; set; }
        //public string EmployeeId { get; set; }备案人（备案）
        public Nullable<System.DateTime> NetClientDate { get; set; }//回访日期
        public int MarketTeaId { get; set; }//市场对接老师（市场人员表）
        //public string StuName { get; set; }学生姓名（备案）
        //public Nullable<bool> StuSex { get; set; }学生性别（备案）
        //public Nullable<int> StuAge { get; set; }学生年龄（备案）
        //public string InformationSource { get; set; }信息来源（备案）
        //public string Education { get; set; }学生学历（备案）
        //public string Region { get; set; }学生地区（备案）
        //public string ContactInformation { get; set; }学生联系方式（备案）
        //public string QQNum { get; set; }学生qq号（备案）
        //public string WeChatNum { get; set; }学生微信号（备案）
        //public Nullable<bool> IsFaceConsult { get; set; }是否面咨/是否上门（备案）
        public string CallBackCase { get; set; }//回访记录
        //public string SecondCallBack { get; set; }
        //public string ThirdCallBack { get; set; }
        public Nullable<bool> IsDel { get; set; }

        public int SPRId { get; set; }//备案编号


    }
}
