//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NurseTeamonDuty
    {
        public int ID { get; set; }
        public string Daste { get; set; }
        public string Openthedoorearly { get; set; }
        public string Openlate { get; set; }
        public string Morningduty { get; set; }
        public string Ondutyatnoon { get; set; }
        public string Theafternoon { get; set; }
        public string Nightgateguard { get; set; }
        public Nullable<bool> Dateofregistration { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public string Remarks { get; set; }
    }
}
