//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTasks
    {
       
    
        public int ProjectID { get; set; }
        public Nullable<int> Tutor { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public string StudentNO { get; set; }
    
       
    }
}
