//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "PurchaseApply")]
    public partial class PurchaseApply
    {

        [Key]
        public int Id { get; set; }
        public string EmployeesInfo_Id { get; set; }
        public Nullable<int> PurchaseType_Id { get; set; }
        public string Rmark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string Image { get; set; }
        /// <summary>
        /// 是否正在操作该数据 false--否，true--是
        /// </summary>
        public Nullable<bool> IsWhether { get; set; }
    }
}
