//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table(name: "RecruitPhoneTrace")]
    public partial class RecruitPhoneTrace
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }//姓名
        public string PhoneNumber { get; set; } //电话号码
        public Nullable<System.DateTime> TraceTime { get; set; }//追踪时间
        public string Channel { get; set; }//渠道
        public string ResumeType { get; set; }//简历类型
        public string PhoneCommunicateResult { get; set; }//联系结果
        //public Nullable<System.DateTime> FirstInterviewDate { get; set; }
        //public Nullable<bool> IsInterview { get; set; }
        //public string FirstInterviewResult { get; set; }
        //public Nullable<System.DateTime> RetestDate { get; set; }
        //public string RetestResult { get; set; }
        //public Nullable<System.DateTime> OfferGiveTime { get; set; }
        //public Nullable<System.DateTime> PlanEntryTime { get; set; }
        public Nullable<bool> IsEntry { get; set; }//是否入职
        public string Remark { get; set; }//备注
        public Nullable<bool> IsDel { get; set; }
        public Nullable<int> Pid { get; set; }//岗位
    }
}
