//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitPhoneTrace
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> TraceTime { get; set; }
        public string Channel { get; set; }
        public string ResumeType { get; set; }
        public string PhoneCommunicateResult { get; set; }
        public Nullable<System.DateTime> FirstInterviewDate { get; set; }
        public Nullable<bool> IsInterview { get; set; }
        public string FirstInterviewResult { get; set; }
        public Nullable<System.DateTime> RetestDate { get; set; }
        public string RetestResult { get; set; }
        public Nullable<System.DateTime> OfferGiveTime { get; set; }
        public Nullable<System.DateTime> PlanEntryTime { get; set; }
        public Nullable<bool> IsEntry { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }
    }
}
