//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    /// 班级学员表
    /// </summary>
    [Table(name: "ScheduleForTrainees")]
    public partial class ScheduleForTrainees
    {
        [Key]
        public int ID { get; set; }
        /// <summary>
        /// 班级名称
        /// </summary>
        public string ClassID { get; set; }
        /// <summary>
        /// 学号
        /// </summary>
        public string StudentID { get; set; }
        /// <summary>
        /// 是否为当前班级
        /// </summary>
        public Nullable<bool> CurrentClass { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public DateTime AddDate { get; set; }
        /// <summary>
        /// 班级id
        /// </summary>
        public int ID_ClassName { get; set; }
        /// <summary>
        /// 是否毕业/true则为毕业
        /// </summary>
        public bool IsGraduating { get; set; }

        public string identitydocument { get; set; }

    }
}
