//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "ShppingDetail")]
    public partial class ShppingDetail
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> PurchaseApply_Id { get; set; }
        public Nullable<int> Goods_Id { get; set; }
        public Nullable<int> GoodsCount { get; set; }
        public string Rmark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Company { get; set; }
        /// <summary>
        /// 是否是临时数据
        /// </summary>
        public Nullable<bool> Temporary { get; set; }
        /// <summary>
        /// 员工编号
        /// </summary>
        public string EmpId { get; set; }
    }
}
