//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 模拟面试登记表
    /// </summary>
    [Table(name: "SimulatInterview")]
    public partial class SimulatInterview
    {
        [Key]
        public int ID { get; set; }
        public string StudentNo { get; set; }
        public int EntStaffID { get; set; }
        public string Remark { get; set; }
        public bool IsDel { get; set; }
        /// <summary>
        /// 记录时间
        /// </summary>
        public System.DateTime AddDate { get; set; }
        /// <summary>
        /// 自我介绍
        /// </summary>
        public string knowMyself { get; set; }
        /// <summary>
        /// 表达能力
        /// </summary>
        public string ShowAbility { get; set; }
        /// <summary>
        /// 人事面试问题情况
        /// </summary>
        public string PerIntQues { get; set; }
        /// <summary>
        /// 简历背诵
        /// </summary>
        public string Resume { get; set; }
        /// <summary>
        /// 项目回答情况
        /// </summary>
        public string ObjectInfo { get; set; }
        /// <summary>
        /// 总评
        /// </summary>
        public string Pandect { get; set; }
    
       
    }
}
