                                                                                                                                                    //------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "Specialty")]
    public partial class Specialty: IEqualityComparer<Specialty>
    {
       
        [Key]
        public int Id { get; set; }
        public string SpecialtyName { get; set; }
        public string Rmark { get; set; }
        public Nullable<bool> IsDelete { get; set; }

        public bool Equals(Specialty x, Specialty y)
        {
            if (x.Id == y.Id)
                return true;

            return false;
        }

        public int GetHashCode(Specialty obj)
        {
            if (this.Id == obj.Id)
                return 1;

            return 0;
        }


        public override bool Equals(object obj)
        {
            Specialty specialty = obj as Specialty;

            if (specialty.Id == this.Id)
                return true;

            return false;

        }

        public static bool IsContain(List<Specialty> sources, Specialty specialty)
        {
            foreach (var item in sources)
            {
                if (item.Id == specialty.Id)
                    return true;
            }
            return false;
        }
    }
}
