//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 学员信息表
    /// </summary>
    [Table(name: "StudentInformation")]
    public partial class StudentInformation
    {
      
       [Key]
        public string StudentNumber { get; set; }
        public string Name { get; set; }
        public bool Sex { get; set; }
        /// <summary>
        /// 身份证
        /// </summary>
        public string identitydocument { get; set; }
        public string Telephone { get; set; }
        public string qq { get; set; }
        public string WeChat { get; set; }
        /// <summary>
        /// 图片
        /// </summary>
        public string Picture { get; set; }
        /// <summary>
        /// 状态
        /// </summary>
        public Nullable<int> State { get; set; }

        public string Hobby { get; set; }
        public string Familyaddress { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        /// <summary>
        /// 种族
        /// </summary>
        public string Nation { get; set; }
        /// <summary>
        /// 学历
        /// </summary>
        public string Education { get; set; }
        /// <summary>
        /// 性格
        /// </summary>
        public string Traine { get; set; }
        public string Password { get; set; }
        public Nullable<int> StudentPutOnRecord_Id { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        /// <summary>
        /// 注册时间
        /// </summary>
        public Nullable<System.DateTime> InsitDate { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Reack { get; set; }
        public string Guardian { get; set; }

    }
}
