//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    //学员费用表
    [Table(name: "StudentFeeRecord")]
    public partial class StudentFeeRecord
    {
        [Key]
        public int ID { get; set; }
        /// <summary>
        /// 学号
        /// </summary>
        public string StudenID { get; set; }
        /// <summary>
        /// 金额
        /// </summary>
        public Nullable<decimal> Amountofmoney { get; set; }
        /// <summary>
        /// 经办人
        /// </summary>
        public Nullable<int> FinanceModelid { get; set; }
        /// <summary>
        /// 消费时间
        /// </summary>
        public Nullable<System.DateTime> AddDate { get; set; }
        /// <summary>
        /// 名目
        /// </summary>
        public int Costitemsid { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remarks { get; set; }
        /// <summary>
        /// 是否删除
        /// </summary>
        public Nullable<bool> IsDelete { get; set; }
    }
}
