//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInformation
    {
      
       
        public string StudentNumber { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string identitydocument { get; set; }
        public string Telephone { get; set; }
        public string qq { get; set; }
        public string WeChat { get; set; }
        public string Picture { get; set; }
        public Nullable<int> State { get; set; }
        public string Hobby { get; set; }
        public string Family_address { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Nation { get; set; }
        public string Education { get; set; }
        public string Traine { get; set; }
        public string Password { get; set; }
        public Nullable<int> StudentPutOnRecord_Id { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> InsitDate { get; set; }
        public string Reack { get; set; }
    
       
    }
}
