//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 数据备案学生状态表
    /// </summary>
    [Table(name: "StuStatus")]
    public partial class StuStatus
    {
        
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 数据备案学生状态
        /// </summary>
        public string StatusName { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Rmark { get; set; }
        /// <summary>
        /// 是否禁用
        /// </summary>
        public Nullable<bool> IsDelete { get; set; }
    
    }
}
