//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyRecords
    {
       
    
        public int ID { get; set; }
        public string StudentNO { get; set; }
        public Nullable<int> EmpStaffID { get; set; }
        public Nullable<System.DateTime> RecordsDate { get; set; }
        public string AppraisalComments { get; set; }
        public string EmpStaffComments { get; set; }
        public string EmpExpectations { get; set; }
        public string MasterTechnology { get; set; }
        public string PracticalExperience { get; set; }
        public string SelfRating { get; set; }
        public string SurRating { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> WantSpceID { get; set; }
    
    }
}
