//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "TalentDemandPlan")]
    public partial class TalentDemandPlan
    {
        [Key]
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> Pid { get; set; }
        public Nullable<int> DemandPersonNum { get; set; }
        public Nullable<System.DateTime> PlanEntryTime { get; set; }
        public string PositionStatement { get; set; }
        public string PositionRequest { get; set; }
        public string RecruitReason { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }
     public Nullable<System.DateTime> ApplyTime { get; set; }

    }
}
