//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// 教学老师晚自习值班记录表
    /// </summary>
    [Table(name: "TeacherNight")]
    public partial class TeacherNight
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 值班老师（员工编号）
        /// </summary>
        public string Tearcher_Id { get; set; }//要去数据库修改
        /// <summary>
        /// 班级
        /// </summary>
        public System.Nullable<int> ClassSchedule_Id { get; set; } //要去数据库修改
        /// <summary>
        /// 值班情况
        /// </summary>
        public string OnByReak { get; set; }
        /// <summary>
        /// 值班类型
        /// </summary>
        public int BeOnDuty_Id { get; set; }
        /// <summary>
        /// 值班日期
        /// </summary>
        public DateTime OrwatchDate { get; set; }

        public string Rmark { get; set; }
        /// <summary>
        /// 是否审核
        /// </summary>
        public bool IsDelete { get; set; }
    
        /// <summary>
        /// 值班时间段
        /// </summary>
        public string timename { get; set; }
        /// <summary>
        /// 教室
        /// </summary>
        public System.Nullable<int> ClassRoom_id { get; set; }
        /// <summary>
        /// 安排日期
        /// </summary>
        public DateTime AttendDate { get; set; }
    }
}
