//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "TeacherNight")]
    public partial class TeacherNight
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> Tearcher_Id { get; set; }
        /// <summary>
        /// 班级
        /// </summary>
        public string ClassSchedule_Id { get; set; }
        /// <summary>
        /// 值班情况
        /// </summary>
        public string OnByReak { get; set; }
        /// <summary>
        /// 值班类型
        /// </summary>
        public Nullable<int> BeOnDuty_Id { get; set; }
        /// <summary>
        /// 安排日期
        /// </summary>
        public Nullable<System.DateTime> OrwatchDate { get; set; }
        public string Rmark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        /// <summary>
        /// 值班时间段
        /// </summary>
        public string timename { get; set; }
        /// <summary>
        /// 教室
        /// </summary>
        public int ClassRoom_id { get; set; }

    }
}
