//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherNight
    {
        public int Id { get; set; }
        public Nullable<int> Tearcher_Id { get; set; }
        public string ClassSchedule_Id { get; set; }
        public string OnByReak { get; set; }
        public Nullable<int> BeOnDuty_Id { get; set; }
        public Nullable<System.DateTime> OrwatchDate { get; set; }
        public string Rmark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
      
    }
}
