//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "TecharOnstageBearing")]
    public partial class TecharOnstageBearing
    {
        [Key]
        public int ID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<int> Major { get; set; }
        public string Remark { get; set; }


        public static bool IsContentMajor(List<TecharOnstageBearing>  source, int ? majorid)
        {
            foreach (var item in source)
            {
                if (item.Major == majorid)
                {
                    return true;
                }
               
            }
            return false;
        }
        public static bool ISContainTeacher(List<TecharOnstageBearing> source, int? teacherid)
        {


            foreach (var item in source)
            {
                if (item.TeacherID == teacherid)
                {
                    return true;
                }

            }
            return false;
        }
    
    }

}
