//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "TotaleCharges")]
    public partial class TotaleCharges
    {
        [Key]
        public int Id { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remarks { get; set; }
        public string WeChat { get; set; }
        public Nullable<decimal> Alipay { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
