//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table(name: "Trialapplication")]
    public partial class Trialapplication
    {
        
        [Key]
        public int Id { get; set; }
        public string Studentnumber { get; set; }
        /// <summary>
        /// 当前班级
        /// </summary>
        public int TrialClass { get; set; }
        public Nullable<int> Trialtime { get; set; }
        public string ReasonsforTrialStudy { get; set; }
        public Nullable<System.DateTime> TrialDate { get; set; }
        public Nullable<double> EKTachievement { get; set; }
        public Nullable<double> EKTRespondent { get; set; }
        public Nullable<int> Task { get; set; }
        public Nullable<int> Attendance { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
       
    }
}
